#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

CFLAGS="-O2 -Wall -Itests $(pkg-config --cflags libusb-1.0)"
LDFLAGS=$(pkg-config --libs libusb-1.0)

cc $CFLAGS -o $WORKDIR/stress.o -c tests/stress.c
cc $CFLAGS -o $WORKDIR/testlib.o -c tests/testlib.c
cc -o $WORKDIR/stress $WORKDIR/stress.o $WORKDIR/testlib.o $LDFLAGS

echo "build: OK"
[ -x $WORKDIR/stress ]
$WORKDIR/stress
echo "run: OK"

